authors = ["William Herrera <wherrera@alahonua.com>"]
name = "SailingRoutes"
uuid = "d06415a4-9c7d-47c7-ab98-dfa4b4cb57de"
version = "0.1.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
DataStructures = "0.17, 0.18, 0.19, 0.20, 0.21, 0.22"
DelimitedFiles = "1"
Interpolations = "0.14, 0.15, 0.16, 0.17, 0.18"

[targets]
test = ["Test"]
